language: r
sudo: false
os:
  - linux
dist: bionic
addons:
  apt:
    packages:
    - python2.7
    - pip
cache:
  packages: true
r:
  - bioc-devel
before_install:
  - tlmgr install index
  - sudo pip install cwltool
