language: r
sudo: false
os:
  - linux
dist: bionic
cache:
  packages: true
r:
  - bioc-devel
before_install:
  - tlmgr install index
  - sudo apt-get -y update
  - sudo apt-get install -y python2.7 pip
  - sudo pip install cwltool
